name: Deploy

on: 
    push:
        branches:
            - master
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo code
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm install
            - name: Build app
              run: npm run build
            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: us-east-1
            - name: Sync to S3 bucket
              run: aws s3 sync ./out/. s3://khoalecs.com


